### ISSUE TITLE
Migrate to SDL2?

### ISSUE THREAD

**Issue by richardrauser** [dreamlayers/acidwarp#3]
Hi there! I must admit I love this project.. I was a huge fan of Acidwarp in the 90s as a young teenager. :-) I wonder if you had considered migrating to SDL2 for multiscreen support? Or perhaps you have reasons for not doing so? I might be able to wade in and help if you think this is a worthy idea.

**Comment by dreamlayers** [comment]
Hi! Thanks for expressing your appreciation.

I have thought about migrating to SDL 2. I don't know if it's beneficial enough to be worth it. I guess the main benefit would be availability of SDL_BlitScaled(), so you could scale up the original size 320x200 image to whatever size you wanted. Also, Emscripten's SDL 2 is better because it's a real port and not a hacky and incomplete re-implementation like its SDL 1.  Acidwarp works fine with Emscripten SDL 1, though it would be interesting to see if CPU usage is decreased with SDL 2.

Recently I was disappointed that [SDL 2 full screen is badly broken with Nvidia drivers in Linux](https://forums.libsdl.org/viewtopic.php?t=12355&sid=50919c752761e8700928b3427ee3a956). SDL 1 full screen works fine.

How do you think multiscreen support would benefit Acidwarp?

**Comment by dreamlayers** [comment]
Just did this, with the bare minimum needed for SDL 2 to work. It's not complete or clean yet, especially in Makefile. https://github.com/dreamlayers/acidwarp/tree/sdl2

Interestingly, this greatly decreases Xorg CPU usage. With default 320x200 window, Q6600 CPU, Nvidia drivers and GeForce 8600GT, according to top, Xorg uses 2% idle, 3 to 5% with SDL 2 and 15% with SDL 1. Not defining HAVE_PALETTE does not change Xorg CPU usage with SDL 1.

**Comment by dreamlayers** [comment]
Okay, I think the SDL 2 support is complete. It is in master now. Build giving SDL=2 argument to make; otherwise it defaults to SDL 1 because that is better tested. SDL 2 simplifies full screen mode a lot, because it seems to automatically pick an appropriate mode close to the current window size. Now display.c is kind of messy with all the conditionals, but that could be cleaned up easily with unifdef. For now I would like to keep SDL 1 support.

**Comment by richardrauser** [comment]
Wow! That is awesome. Sorry for the slow response as I am just returning from a trip out-of-town, but thanks for this as now I can get acidwarp going on any of my three monitors (just tested this). Great!

**Comment by dreamlayers** [comment]
You're welcome. BTW I also also recently added OpenGL support with SDL 2, when built with `make GL=1`. This uploads the 8 bpp image generated by Acidwarp to the GPU once and for colour cycling only uploads new 256x1 textures for use as a palette lookup table..
